spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.defer-datasource-initialization=false
spring.sql.init.mode=never
app.auth.cookie.secure=${APP_AUTH_COOKIE_SECURE:true}
app.auth.cookie.same-site=${APP_AUTH_COOKIE_SAME_SITE:None}
